Loading rlang/3.6.3
  Loading requirement: jdk/13.0.1
Warning: 3844 parsing failures.
  row       col           expected actual                                                                     file
39528 seqorient 1/0/T/F/TRUE/FALSE     RC '../../analysis/created_germlines/reannotated_db/merged_changeo_ILE.tsv'
39536 seqorient 1/0/T/F/TRUE/FALSE     RC '../../analysis/created_germlines/reannotated_db/merged_changeo_ILE.tsv'
39566 seqorient 1/0/T/F/TRUE/FALSE     RC '../../analysis/created_germlines/reannotated_db/merged_changeo_ILE.tsv'
39595 seqorient 1/0/T/F/TRUE/FALSE     RC '../../analysis/created_germlines/reannotated_db/merged_changeo_ILE.tsv'
39715 seqorient 1/0/T/F/TRUE/FALSE     RC '../../analysis/created_germlines/reannotated_db/merged_changeo_ILE.tsv'
..... ......... .................. ...... ........................................................................
See problems(...) for more details.

Warning message:
In validate_airr(data, schema = schema) :
  Warning: sequence_id(s) are not unique: TTTTCTCGTTTTGCTT, TGTGCTTGGTTGTCTT, TTCGTTATTGTCGTTT, TTTGTTGGGCTGTCTT, TCTTGTGGTTTTCTTT, TTACTTGGCTTCTTTT, TTTTTTTTATTGGGCT, TGGTTTGTTTTCTGTT, TCTCTTAATTTCTTTT, TGGCTTTTGGTGTTCT, TGTTGTTCTTTTTGGT, TGCCTTTGACTTTGTT, TGTGTTAAGCTGTCGT, TGGCTTCTCTTCGTAT, TTAGGTGGGCTTATTT, TGATTTATTTTGACTT, TGTCCTTTGCTTGCTT, TCCGCTTGGTTTTGTT, TTCTATTCGGTGTCTT, TGTTTTTCTTTGTCTT, TCTTTTCTTTTGGGAT, TTTCCTCTCTTCTGCT, TGTTCTTTCCTGTTCT, TTTTGTTACCTGTTGT, TTATTTTGTCTCGTTT, TGGCGTGTGTTTTTTT, TAGTTTATGGTCTTTT, TGGGATGCCTTGGGTT, TTGTTTTGTTTTTATT, TTGGGTTCGGCGGGCT, TTACTTTGTTTTGCTT, TTTGATGTTATATTTT, TACCTTGTGGTTTTTT, TCCGTTGTTCTGGGGT, TTTTTTGGATTTGGCT, TGCCTTTTCGTTTTAT, TTTCTTGTTTTATGTT, TGTTTTAGTTTGCGGT, TGCTTTTAATTCTTGT, TCATTTGTGATTTTGT, TGTTATTCGTTGCGGT, TTGTCTTCTTTTTCTT, TGGGTTGTAGTTTTCT, TTTGTTGTTTTCTTTT, TCCTCTGTTTTTGTTT, TTATTTTGTTTGTGCT, TTGTATAGTATCTCTT, TGTGTTCTTTTGATTT, TGCCTTCGTCTCGTTT, TAGTTTTCATTTATGT, TTTTTTCTTGTTCGTT, TTGTTTGTTTTCTCTT, TTTGATTCATTTTGGT, TTTTAT [... truncated]
There were 50 or more warnings (use warnings() to see the first 50)
Warning message:
In validate_airr(data, schema = schema) :
  Warning: sequence_id(s) are not unique: TATTCTTTTTTGCTGT, TGACTTGTCATGTGTT, TGTCATTTTGTTCGTT, TTACCTGGGGTTGTGT, TGTCCTTCGTTTCTCT, TGTTCTTGGATTTCGT, TGGATTTTTTTTCTGT, TTTATTTTTGTTGTCT, TCTTTTTTTCTCTTCT, TGCTGTGTTGTGTGCT, TTGTCTGCTTTTGTGT, TGTTCTTCCTTGTGCT, TGGTTTGTGGTTCGGT, TTGTATGTGTTTGTCT, TAATGTTGGTTACCAT, TGGTTTTTTCTGGTTT, TTTTTTTCGTTCGGTT, TTGGTTCGTCTTCCTT, TATTGTCTCTTTCATT, TCGTTTTCTATTGCAT, TTGATTTTCTTATGGT, TGGTCTTCGCTTCTGT, TGGGGTTACTTTGGGT, TTGGCTCTTATGTTGT, TCGCGTTCTTTTAGGT, TTGTTTTGCCTGGGTC, TCATTTTTCCTTTGTT, TATCTTCGTATTTGGT, TGCGTTTCGCTGTTTT, TGCTGTTTGTTGGTCT, TATTGTTCTTTGTCTT, TGTGTTGTCTTTTTTT, TGCGTTTGGGTCTGGT, TTGTTTTTTCTAAATT, TCTATTGCGTTTGGGT, TTTTTTATTGTGCGTT, TTCTGTTGTGTACGGT, TCTGGTCTGGTCGCTT, TGTCATGTTTTCTGGT, TTACCTTTTTTTGGGT, TTTTGTTGGTTATACT, TTTTCTTGGCTTGGTT, TCTTGTTGTATGGTGT, TAAGGTTTGCTATGTT, TCCTGTTCATTCTTGT, TGGTATTTTTTGATGT, TTGCATCATATGTTTT, TTAGGTTTTTTATTTT, TCGGTTCCTTTCGCGT, TTGGCTTCTTTGGGGT, TTATGTACGGTTGTGT, TCGGTTCGTTTTTCTT, TGCTTTCTTTTATTCT, TGAGTT [... truncated]
There were 50 or more warnings (use warnings() to see the first 50)
